modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Christofmeg/ExNihiloExtras/issues" #optional
license="The MIT License (MIT)"
[[mods]]
modId="exnihiloextras"
version="${file.jarVersion}"
displayName="Ex Nihilo Extras"
displayURL="https://github.com/Christofmeg/ExNihiloExtras" #optional
logoFile="icon.png"
#credits=""
authors="Christofmeg"
description="Addon for Ex Nihilo: Sequentia adding extra features."
[[dependencies.exnihiloextras]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.exnihiloextras]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.exnihiloextras]]
    modId="exnihilosequentia"
    mandatory=true
    versionRange="*"
    ordering="NONE"
    side="BOTH"
[modproperties.exnihiloextras]
    catalogueImageIcon="exnihiloextras-icon.png"
