# Project
version=1.2.0
group=com.christofmeg.exnihiloextras

# Mod options
mod_name=Ex Nihilo Extras
mod_author=Christofmeg
mod_id=exnihiloextras

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Common
minecraft_version=1.20.4
supported_versions=1.20.4

# NeoForge | https://projects.neoforged.net/neoforged/neoforge
neo_minecraft_version=1.20.4
neo_supported_versions=1.20.4
neo_version=20.4.237

#---------------------------------------------------------------------------

# CurseForgeGradle | Minotaur options
cf_id=897084
modrinth_id=df69gHGo
release_type=release
neoforge_release_versions=1.20.4